### ISSUE TITLE
How does pagination work with dataloader?

### ISSUE THREAD

**Issue by tonyghita** [nicksrandall/dataloader#13]
I've been having trouble wrapping my head around how pagination works with a batched data loader.

```graphql
scalar Cursor # an opaque string which identifies a resource

query GetUsers($first: Int, $after: Cursor) {
  users(first: $first, after: $after) {
   name
  }
}
```

Do the same pagination parameters `$first` and `$after` get passed into every possible batch? Is there some page accounting that has to happen a layer above the data loader layer? 

@nicksrandall I'd love to get your thoughts.

**Comment by nicksrandall** [comment]
While you could probably get that to work, I don't think that dataloaders are designed to handle that use case. What you could do though is execute your query like you normally would (w/o a loader) and then prime your user loader's cache with the results for future one off queries. 

That said, I would ask this same question on facebook/dataloader repo and see that Lee has to say. If you choose to do that, tag me in the question because I'd like to know his response.

**Comment by tonyghita** [comment]
For reference: https://github.com/facebook/dataloader/issues/71

**Comment by nicksrandall** [comment]
Cool! Thanks.
