### ISSUE TITLE
Add context.Context as an argument to dataloader.BatchFunc?

### ISSUE THREAD

**Issue by tonyghita** [nicksrandall/dataloader#21]
Currently I pass in a `context.Context` via closure. I'm curious if anyone has a better way of passing the context to the batch function.

```go
func Attach(ctx context.Context) dataloader.BatchFunc {
  return func(keys []string) []*dataloader.Result {
    // the batch function, now with 100% more context
  }
}
```

Are there any downsides to changing the signature of `BatchFunc` to include the context as an argument?

```diff
- type BatchFunc func([]string) []*Result
+ type BatchFunc func(context.Context, []string) []*Result
```

**Comment by nicksrandall** [comment]
I don't use context in all of my loaders, and where I do, I create a `makeBatchFunc(ctx context.Context) dataloader.BatchFunc` that makes the context available via a closure. These closure functions are nice because they give me a place to do some setup before I return my batch function.

That said, I'm open to hearing a solid argument on making the change. I'm also hesitant to introduce breaking changes.

**Comment by tonyghita** [comment]
That's interesting... I found I am always enclosing a context in my batch functions to provide request deadlines/timeouts, request tracing, etc.

If others have use-cases where a context is not needed, then I agree that it's not worth it to break the interface. I don't have any arguments for making the change other than convenience.

**Comment by nicksrandall** [comment]
@tonyghita if we were to make this change, how would the batchFunc get access to the context so that it can be called? Would you suggest also adding the context to the `load(key string)` and `loadMany(keys []string)` methods as well?

**Comment by tonyghita** [comment]
Yes, it would have to break all sorts of interfaces ☹️

**Comment by tonyghita** [comment]
This has been resolved by v2, thanks @nicksrandall!
